export const initialPlayer = [
  {
    playerId: '',
    order: 1,
    isReady: false,
    location: 0,
    tokenRef: null,
    userStatusBoard: {
      cashAsset: 0,
      stockAsset: 0,
      totalAsset: 0,
      stockList: [],
    },
  },
  {
    playerId: '',
    order: 2,
    isReady: false,
    location: 0,
    tokenRef: null,
    userStatusBoard: {
      cashAsset: 0,
      stockAsset: 0,
      totalAsset: 0,
      stockList: [],
    },
  },
  {
    playerId: '',
    order: 3,
    isReady: false,
    location: 0,
    tokenRef: null,
    userStatusBoard: {
      cashAsset: 0,
      stockAsset: 0,
      totalAsset: 0,
      stockList: [],
    },
  },
  {
    playerId: '',
    order: 4,
    isReady: false,
    location: 0,
    tokenRef: null,
    userStatusBoard: {
      cashAsset: 0,
      stockAsset: 0,
      totalAsset: 0,
      stockList: [],
    },
  },
];

export const initialStock = [
  {
    logo: 'codesquad',
    name: '코드스쿼드',
    theme: 'it',
    quantity: 0,
    price: 0,
  },
  {
    logo: 'musinsa',
    name: '무신사',
    theme: 'fashion',
    quantity: 0,
    price: 0,
  },
  {
    logo: 'hanatour',
    name: '하나투어',
    theme: 'trip',
    quantity: 0,
    price: 0,
  },
  {
    logo: 'gs',
    name: 'GS건설',
    theme: 'construction',
    quantity: 0,
    price: 0,
  },
  {
    logo: 'nongshim',
    name: '농심',
    theme: 'food',
    quantity: 0,
    price: 0,
  },
  {
    logo: 'hyundai',
    name: '현대건설',
    theme: 'construction',
    quantity: 0,
    price: 0,
  },
  {
    logo: 'hanhwa',
    name: '한화디펜스',
    theme: 'military',
    quantity: 0,
    price: 0,
  },
  {
    logo: 'koreanair',
    name: '대한항공',
    theme: 'trip',
    quantity: 0,
    price: 0,
  },
  {
    logo: 'twitter',
    name: '트위터',
    theme: 'elonmusk',
    quantity: 0,
    price: 0,
  },
  {
    logo: 'samsungbio',
    name: '삼성바이오',
    theme: 'pharmaceutical',
    quantity: 0,
    price: 0,
  },
  {
    logo: 'google',
    name: '구글',
    theme: 'it',
    quantity: 0,
    price: 0,
  },
  {
    logo: 'hermes',
    name: '에르메스',
    theme: 'fashion',
    quantity: 0,
    price: 0,
  },
  {
    logo: 'mcdonalds',
    name: '맥도날드',
    theme: 'food',
    quantity: 0,
    price: 0,
  },
  {
    logo: 'tesla',
    name: '테슬라',
    theme: 'elonmusk',
    quantity: 0,
    price: 0,
  },
  {
    logo: 'pfizer',
    name: '화이자',
    theme: 'pharmaceutical',
    quantity: 0,
    price: 0,
  },
  {
    logo: 'starkindustry',
    name: '스타크인더스트리',
    theme: 'military',
    quantity: 0,
    price: 0,
  },
  {
    logo: 'apple',
    name: '애플',
    theme: 'it',
    quantity: 0,
    price: 0,
  },
];

export const initialGame = {
  isPlaying: false,
  currentPlayerId: '',
  currentPlayerStatus: { type: 'default' },
  dice: [0, 0],
};
